#!/usr/bin/env python3
"""
Template Decorative Elements Injector for Presentation OS.

Post-processes a PPTX generated by Presentation OS to inject decorative elements
from a source .pptx template. Copies spTree children (pics, groups, decorative shapes)
while skipping text placeholders and full-slide background pics.

Usage:
  python3 template-injector.py <input.pptx> <template.pptx> <output.pptx> <role_map.json>

role_map.json example:
  { "1": 1, "2": 2, "6": 3, "7": 4, "14": 5 }
  Maps output slide index -> template slide index.
"""
import sys
import json
import zipfile
from xml.etree import ElementTree as ET

P_NS = 'http://schemas.openxmlformats.org/presentationml/2006/main'
A_NS = 'http://schemas.openxmlformats.org/drawingml/2006/main'
R_NS = 'http://schemas.openxmlformats.org/officeDocument/2006/relationships'
PKG_REL_NS = 'http://schemas.openxmlformats.org/package/2006/relationships'


def parse_rels_xml(xml_bytes):
    root = ET.fromstring(xml_bytes)
    rels = {}
    for rel in root.findall(f'{{{PKG_REL_NS}}}Relationship'):
        rels[rel.get('Id')] = {
            'type': rel.get('Type', ''),
            'target': rel.get('Target', ''),
        }
    return rels


def rels_to_xml(rels_dict):
    lines = ['<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
             '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">']
    for rid in sorted(rels_dict.keys()):
        info = rels_dict[rid]
        lines.append(f'  <Relationship Id="{rid}" Type="{info["type"]}" Target="{info["target"]}"/>')
    lines.append('</Relationships>')
    return '\r\n'.join(lines).encode('utf-8')


def get_sp_tree(root):
    return root.find(f'.//{{{P_NS}}}spTree')


def collect_pic_rids(spTree):
    rids = set()
    for blip in spTree.iter(f'{{{A_NS}}}blip'):
        rid = blip.get(f'{{{R_NS}}}embed')
        if rid:
            rids.add(rid)
    return rids


def generate_new_rid(existing_rids, prefix='rId', start_from=1):
    n = start_from
    while f'{prefix}{n}' in existing_rids:
        n += 1
    return f'{prefix}{n}'


def find_next_rid_number(existing_rids, prefix='rId', start_from=1):
    """Find the highest rId number + 1 to avoid any collision."""
    max_n = start_from - 1
    for rid in existing_rids:
        if rid.startswith(prefix):
            try:
                n = int(rid[len(prefix):])
                if n > max_n:
                    max_n = n
            except ValueError:
                pass
    return max_n + 1


def replace_rids_in_element(element, rid_map):
    """Recursively replace rId references in an element tree.
    
    Replaces both ns2:embed="rIdN" attributes and ns2:id="rIdN" attributes
    in the XML tree using precise attribute-level replacement.
    """
    R_NS2 = '{http://schemas.openxmlformats.org/officeDocument/2006/relationships}'
    
    # Replace current element's attributes
    for attr_key, val in list(element.attrib.items()):
        if attr_key == f'{R_NS2}embed' or attr_key == f'{R_NS2}id':
            for old_rid, new_rid in rid_map.items():
                if val == old_rid:
                    element.set(attr_key, new_rid)
                    break
    
    # Recurse into children
    for child in element:
        replace_rids_in_element(child, rid_map)


def is_full_slide_pic(element):
    """Check if an element is a full-slide background picture."""
    xfrm = element.find(f'{{{P_NS}}}spPr/{{{A_NS}}}xfrm')
    if xfrm is None:
        return False
    off = xfrm.find(f'{{{A_NS}}}off')
    ext = xfrm.find(f'{{{A_NS}}}ext')
    if off is None or ext is None:
        return False
    try:
        x = int(off.get('x', '0')) / 914400
        y = int(off.get('y', '0')) / 914400
        w = int(ext.get('cx', '0')) / 914400
        h = int(ext.get('cy', '0')) / 914400
        return x <= 0.1 and y <= 0.1 and w >= 13.0 and h >= 7.0
    except (ValueError, TypeError):
        return False


def has_text_content(element):
    """Check if element contains any text in <a:t> descendants."""
    for t in element.iter(f'{{{A_NS}}}t'):
        if t.text and t.text.strip():
            return True
    return False


def main():
    if len(sys.argv) < 5:
        print("Usage: python3 template-injector.py <input.pptx> <template.pptx> <output.pptx> <role_map.json>")
        sys.exit(1)

    input_path = sys.argv[1]
    template_path = sys.argv[2]
    output_path = sys.argv[3]
    
    with open(sys.argv[4], 'r') as f:
        role_map_raw = json.load(f)
    # Convert string keys to int
    role_map = {int(k): v for k, v in role_map_raw.items()}

    # ---- Load template data ----
    with zipfile.ZipFile(template_path, 'r') as tz:
        template_media = {}
        template_spTrees = {}
        template_rels = {}
        
        for i in range(1, 6):
            key = f'ppt/slides/slide{i}.xml'
            if key in tz.namelist():
                xml_bytes = tz.read(key)
                template_rels[i] = parse_rels_xml(tz.read(f'ppt/slides/_rels/slide{i}.xml.rels'))
                root = ET.fromstring(xml_bytes)
                spTree = get_sp_tree(root)
                template_spTrees[i] = spTree
        
        for name in tz.namelist():
            if name.startswith('ppt/media/'):
                template_media[name] = tz.read(name)

    # ---- Load output data ----
    with zipfile.ZipFile(input_path, 'r') as oz:
        output_slides = {}
        output_roots = {}
        output_spTrees = {}
        output_rels = {}
        
        total_slides = 0
        for i in range(1, 100):
            key = f'ppt/slides/slide{i}.xml'
            if key not in oz.namelist():
                break
            total_slides = i
        
        for i in range(1, total_slides + 1):
            key = f'ppt/slides/slide{i}.xml'
            xml_bytes = oz.read(key)
            output_slides[i] = xml_bytes
            output_rels[i] = parse_rels_xml(oz.read(f'ppt/slides/_rels/slide{i}.xml.rels'))
            root = ET.fromstring(xml_bytes)
            output_roots[i] = root
            spTree = get_sp_tree(root)
            output_spTrees[i] = spTree

    # ---- Inject template decorations ----
    media_needed = set()
    
    for out_idx in range(1, total_slides + 1):
        if out_idx not in output_spTrees or out_idx not in output_slides:
            continue
        
        tmpl_idx = role_map.get(out_idx)
        if tmpl_idx is None:
            continue
        
        tmpl_spTree = template_spTrees.get(tmpl_idx)
        if tmpl_spTree is None:
            continue
        
        out_spTree = output_spTrees[out_idx]
        out_root = output_roots[out_idx]
        
        existing_rids = set(output_rels[out_idx].keys())
        needed_rids = collect_pic_rids(tmpl_spTree)
        
        # Find next available rId number (highest existing + 1)
        next_rid_num = find_next_rid_number(existing_rids)
        
        rid_map = {}
        for t_rid in sorted(needed_rids):
            if t_rid in template_rels.get(tmpl_idx, {}):
                new_rid = f'rId{next_rid_num}'
                next_rid_num += 1
                rid_map[t_rid] = new_rid
                existing_rids.add(new_rid)
                
                t_rel = template_rels[tmpl_idx][t_rid]
                target = t_rel['target']
                if target.startswith('../media/') or target.startswith('media/'):
                    media_name = target.split('/')[-1]
                    media_needed.add(f'ppt/media/{media_name}')
        
        # Rewrite rid references using precise XML attribute replacement
        replace_rids_in_element(tmpl_spTree, rid_map)
        
        # Append decorated children to output spTree
        for child in list(tmpl_spTree):
            tag = child.tag.split('}')[-1]
            if tag in ('nvGrpSpPr', 'grpSpPr'):
                continue
            # Skip text placeholder text boxes
            if has_text_content(child):
                continue
            # Skip full-slide background pictures (output already has <bg>)
            if is_full_slide_pic(child):
                continue
            out_spTree.append(child)
        
        # Serialize modified output root and write back
        output_slides[out_idx] = ET.tostring(out_root, encoding='unicode').encode('utf-8')
        
        # Update relationships
        new_rels = dict(output_rels[out_idx])
        for t_rid, new_rid in rid_map.items():
            if t_rid in template_rels.get(tmpl_idx, {}):
                new_rels[new_rid] = template_rels[tmpl_idx][t_rid]
        output_rels[out_idx] = new_rels

    # ---- Write result ----
    with zipfile.ZipFile(input_path, 'r') as oz:
        # Read non-slide files from output while oz is still open
        non_slide_files = {}
        for name in oz.namelist():
            if not (name.startswith('ppt/slides/') or name.startswith('ppt/slides/_rels/')):
                non_slide_files[name] = oz.read(name)
    
    with zipfile.ZipFile(output_path, 'w', zipfile.ZIP_DEFLATED) as rz:
        # Copy only valid non-slide files from output (skip invalid pptxgenjs artifacts)
        for name, data in non_slide_files.items():
            if name.startswith('ppt/media/'):
                # Only keep valid image files (.png, .jpg, .jpeg, .gif)
                ext = name.rsplit('.', 1)[-1].lower()
                if ext in ('png', 'jpg', 'jpeg', 'gif'):
                    rz.writestr(name, data)
            else:
                rz.writestr(name, data)
        
        # Write processed slides and rels
        for i in range(1, total_slides + 1):
            if i in output_slides:
                rz.writestr(f'ppt/slides/slide{i}.xml', output_slides[i])
                if i in output_rels and output_rels[i]:
                    rz.writestr(f'ppt/slides/_rels/slide{i}.xml.rels',
                               rels_to_xml(output_rels[i]))
        
        # Copy template media files that were injected
        for media_name in sorted(media_needed):
            if media_name in template_media:
                rz.writestr(media_name, template_media[media_name])

    print(f"✅ Template decorations injected: {output_path}")
    
    # Verify
    with zipfile.ZipFile(output_path, 'r') as vz:
        print(f"\nMedia files ({len([n for n in vz.namelist() if n.startswith('ppt/media/')])}):")
        for name in sorted(vz.namelist()):
            if name.startswith('ppt/media/'):
                print(f"  {name}")
        
        print(f"\nSlide elements:")
        for i in range(1, total_slides + 1):
            key = f'ppt/slides/slide{i}.xml'
            if key not in vz.namelist():
                continue
            xml_str = vz.read(key).decode('utf-8')
            root = ET.fromstring(xml_str)
            sp_count = len(root.findall(f'.//{{{P_NS}}}sp'))
            grp_count = len(root.findall(f'.//{{{P_NS}}}grpSp'))
            pic_count = len(root.findall(f'.//{{{P_NS}}}pic'))
            total = sp_count + grp_count + pic_count
            if total > 3:
                print(f"  Slide {i}: sp={sp_count} grp={grp_count} pic={pic_count} total={total}")


if __name__ == '__main__':
    main()
