/**
 * @awe/presentation-pipeline - Template Spec Parser (M12.30)
 *
 * Parses human-readable template specification markdown files (.md) generated by
 * the template-first workflow and converts them into structured JSON data that
 * template-injector.py can consume.
 */

const fs = require("fs");
const path = require("path");

// --- Slide Role Mapping ---

const ROLE_PATTERNS = {
  cover: [/封面/i, /cover/i, /title\s*slide/i, /title-slide/i],
  "section-divider": [/章节/i, /section/i, /divider/i, /分隔/i, /目录/i, /agenda/i],
  title: [/标题页/i, /title\s*page/i, /汇报人/i, /title\s*and\s*subtitle/i],
  closing: [/结束/i, /closing/i, /thank/i, /致谢/i, /back/i],
  "data-chart": [/图表/i, /chart/i, /data/i, /kpi/i, /big\s*number/i, /数字/i],
  timeline: [/timeline/i, /时间线/i, /历程/i, /roadmap/i, /milestone/i],
  quote: [/quote/i, /引言/i, /语录/i, /金句/i],
  matrix: [/matrix/i, /矩阵/i, /四象限/i, /quadrant/i],
};

function guessRole(slideDescription) {
  const text = slideDescription.toLowerCase();
  for (const [role, patterns] of Object.entries(ROLE_PATTERNS)) {
    if (patterns.some(p => p.test(text))) {
      return role;
    }
  }
  return "content";
}

// --- Parse Media Assets ---

function parseMediaAssets(specText) {
  const assets = [];
  const mediaSection = specText.match(/##\s+媒体素材清单[\s\S]*?(?=##\s|---|$)/i);
  if (!mediaSection) return assets;

  const lines = mediaSection[0].split("\n");
  let inTable = false;

  for (const line of lines) {
    if (line.includes("| 文件")) {
      inTable = true;
      continue;
    }
    if (inTable && line.trim().startsWith("|-")) continue;
    if (inTable && line.startsWith("|")) {
      const cells = line.split("|").slice(1, -1).map(c => c.trim());
      if (cells.length >= 3) {
        assets.push({
          filename: cells[0],
          size: cells[1] || "",
          purpose: cells[2] || "",
          type: cells[0].match(/\.(png|jpg|jpeg|gif)$/i)?.[1] || "unknown",
        });
      }
    }
    if (inTable && !line.startsWith("|")) {
      inTable = false;
    }
  }

  return assets;
}

// --- Parse Slide Elements ---

function parseSlideElements(sectionText) {
  const elements = [];
  const elementMatch = sectionText.match(/\|\s*元素\s*\|.*?(?=\n---|\n##|\n$)/s);
  if (!elementMatch) return elements;

  const lines = elementMatch[0].split("\n");
  let inTable = false;

  for (const line of lines) {
    if ((line.includes("| 元素 |") || line.includes("| 元素|")) && !line.includes("---")) {
      inTable = true;
      continue;
    }
    if (inTable && line.trim().startsWith("|-")) continue;
    if (inTable && line.startsWith("|")) {
      const cells = line.split("|").slice(1, -1).map(c => c.trim());
      if (cells.length >= 4) {
        const tag = cells[0];
        const content = cells[3] || "";
        const purpose = cells[cells.length - 1] || "";
        const isFullSlideBg = /全尺寸/.test(content) || /全尺寸/.test(purpose) || /background/i.test(purpose);
        const isPlaceholder = /占位符/i.test(purpose) || /需替换/.test(purpose) || /\u274c/.test(purpose);

        elements.push({
          tag,
          content,
          isPlaceholder,
          isFullSlideBg,
          injectable: !isPlaceholder && !isFullSlideBg,
        });
      }
    }
    if (inTable && !line.startsWith("|")) {
      inTable = false;
    }
  }

  return elements;
}

// --- Parse Template Slides ---

function parseTemplateSlides(specText) {
  const slides = [];
  const slideSections = specText.split(/###\s+Slide\s+\d+\s*[\u2014\u2013\-]\s*/i);

  for (let i = 1; i < slideSections.length; i++) {
    const section = slideSections[i];
    const firstLine = section.split("\n")[0].trim();
    const elements = parseSlideElements(section);
    const strategyMatch = section.match(/注入策略[：:]?.*/);
    const injectionStrategy = strategyMatch ? strategyMatch[0].replace(/注入策略[：]?:?\s*/, "").trim() : "";

    slides.push({
      index: i,
      description: firstLine,
      role: guessRole(firstLine),
      elements,
      injectableElements: elements.filter(e => e.injectable),
      injectionStrategy,
    });
  }

  return slides;
}

// --- Parse Template Metadata ---

function parseTemplateMetadata(specText) {
  const meta = {};
  const metaSection = specText.match(/##\s+模板元数据[\s\S]*?(?=##\s)/i);
  if (!metaSection) return meta;

  const lines = metaSection[0].split("\n");
  for (const line of lines) {
    if (line.startsWith("|") && line.includes("|")) {
      const cells = line.split("|").slice(1, -1).map(c => c.trim());
      if (cells.length === 2 && cells[0] && !cells[0].startsWith("-")) {
        meta[cells[0]] = cells[1];
      }
    }
  }

  return meta;
}

// --- Build Injectable Template Data ---

function buildInjectData(specText, specPath) {
  const metadata = parseTemplateMetadata(specText);
  const mediaAssets = parseMediaAssets(specText);
  const templateSlides = parseTemplateSlides(specText);

  return {
    sourceFile: specPath,
    metadata,
    mediaAssets,
    templateSlides: templateSlides.map(slide => ({
      index: slide.index,
      role: slide.role,
      description: slide.description,
      injectableCount: slide.injectableElements.length,
      totalElements: slide.elements.length,
      injectionStrategy: slide.injectionStrategy,
    })),
    summary: {
      totalSlides: templateSlides.length,
      totalMediaFiles: mediaAssets.length,
      roles: {},
    },
  };
}

function summarizeRoles(injectData) {
  for (const slide of injectData.templateSlides) {
    injectData.summary.roles[slide.role] =
      (injectData.summary.roles[slide.role] || 0) + 1;
  }
  return injectData;
}

// --- Public API ---

/**
 * Parse a template specification markdown file.
 * @param {string} specFilePath - Path to the .md template spec file
 * @returns {object} Parsed template data
 */
function parseTemplateSpec(specFilePath) {
  if (!fs.existsSync(specFilePath)) {
    throw new Error(`Template spec not found: ${specFilePath}`);
  }
  const specText = fs.readFileSync(specFilePath, "utf-8");
  const injectData = buildInjectData(specText, specFilePath);
  return summarizeRoles(injectData);
}

/**
 * Parse multiple template specs from a directory.
 * @param {string} directory - Directory containing .md template spec files
 * @returns {object[]} Array of parsed template data
 */
function parseTemplateDirectory(directory) {
  if (!fs.existsSync(directory)) {
    throw new Error(`Directory not found: ${directory}`);
  }
  const files = fs.readdirSync(directory)
    .filter(f => f.endsWith(".md") && f !== "README.md")
    .sort();
  return files.map(f => parseTemplateSpec(path.join(directory, f)));
}

/**
 * Generate a role map from parsed template data.
 * Produces the JSON object used by template-injector.py.
 * @param {object} injectData - Output from parseTemplateSpec
 * @returns {object} { roleMap, templatePath, summary }
 */
function generateRoleMap(injectData) {
  const roleMap = {};
  for (const slide of injectData.templateSlides) {
    roleMap[String(slide.index)] = slide.role;
  }
  return {
    roleMap,
    templatePath: injectData.sourceFile,
    summary: injectData.summary,
  };
}

module.exports = {
  parseTemplateSpec,
  parseTemplateDirectory,
  generateRoleMap,
  guessRole,
  parseMediaAssets,
  parseSlideElements,
  parseTemplateSlides,
  parseTemplateMetadata,
  buildInjectData,
};
